CREATE DATABASE IF NOT EXISTS testel5 CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;

USE testel5;

CREATE TABLE IF NOT EXISTS Log (
    `id` INT PRIMARY KEY AUTO_INCREMENT NOT NULL, 
    `datetime` DATETIME NOT NULL, 
    `level` VARCHAR(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL, 
    `context` VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL, 
    `description` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL
) ENGINE = InnoDB CHARSET=utf8mb4 COLLATE utf8mb4_0900_ai_ci; 